### ISSUE TITLE
Feature request: Enable Cui component to accept onSuccessfulSubmit callback

### ISSUE THREAD

**Issue by chaboo** [jepser/react-cui#4]
First, thanks for this convenient component. It is quite useful.

For us it would be helpful if we could somehow be notified when conversation completes and form is successfully submitted so we can hide it/close it and allow user to continue down our normal usage flow.

If this is already possible using some alternative way, please let me know.

**Comment by jepser** [comment]
Hi @chaboo! Sorry for my late answer, we have an events API: https://github.com/jepser/react-cui#events-api

It will do the job ;)

**Comment by chaboo** [comment]
Thank you
